
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Luis Carlos Flores
 */
public class Main_Lab extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main_Lab() {
        initComponents();
        jc_lics.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jd_carrera = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a_ing = new javax.swing.JRadioButton();
        a_doc = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jc_lics = new javax.swing.JComboBox<>();
        jc_ing = new javax.swing.JComboBox<>();
        jc_doc = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        a_costo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        a_jefe = new javax.swing.JTextField();
        r_l = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pu_carrera = new javax.swing.JPopupMenu();
        a_mod = new javax.swing.JMenuItem();
        a_del = new javax.swing.JMenuItem();
        jd_estudiantes = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jc_carrera = new javax.swing.JComboBox<>();
        a_edad = new javax.swing.JSpinner();
        a_cuenta = new javax.swing.JTextField();
        a_men = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        a_apellido = new javax.swing.JTextField();
        a_nombre = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        pu_estudiantes = new javax.swing.JPopupMenu();
        mod = new javax.swing.JMenuItem();
        del = new javax.swing.JMenuItem();
        jLabel21 = new javax.swing.JLabel();
        jd_clases = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        b_nombre = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        b_seccion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        b_edificio = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        b_salon = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        yes = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        pu_clases = new javax.swing.JPopupMenu();
        bmod = new javax.swing.JMenuItem();
        bdel = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_carrera = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_estudiantes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_clases = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_maestros = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Crear Carrera");

        jLabel9.setText("Facultad:");

        buttonGroup1.add(a_ing);
        a_ing.setText("Ingenerias");
        a_ing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_ingActionPerformed(evt);
            }
        });

        buttonGroup1.add(a_doc);
        a_doc.setText("Ciensas de Salud");
        a_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_docActionPerformed(evt);
            }
        });

        jLabel10.setText("Nombre: ");

        jc_lics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", "Derecho", "Empresas", "Diseno", "Mercadotecnia", " " }));

        jc_ing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Industrial", "Mecatronica", "Biomedica", "Energia", " " }));

        jc_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicina", "Odontologia", "Nutricion", "Terapia", " ", " " }));

        jLabel11.setText("Costo Mensual");

        jLabel12.setText("Jefe:");

        buttonGroup1.add(r_l);
        r_l.setText("Licensiaturas");
        r_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_lActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Guardar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_carreraLayout = new javax.swing.GroupLayout(jd_carrera.getContentPane());
        jd_carrera.getContentPane().setLayout(jd_carreraLayout);
        jd_carreraLayout.setHorizontalGroup(
            jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carreraLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_carreraLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_carreraLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jc_lics, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(r_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a_ing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                        .addGap(83, 83, 83)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_carreraLayout.createSequentialGroup()
                                .addComponent(jc_ing, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jc_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(a_costo)
                            .addComponent(a_jefe, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jd_carreraLayout.setVerticalGroup(
            jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_carreraLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_lics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_l))
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a_ing)
                            .addComponent(jc_ing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_carreraLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_doc)
                    .addComponent(jc_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jd_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(a_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jRadioButton2.setText("jRadioButton2");

        a_mod.setText("Modificar");
        a_mod.setToolTipText("");
        a_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_modActionPerformed(evt);
            }
        });
        pu_carrera.add(a_mod);

        a_del.setText("Eliminar");
        a_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_delActionPerformed(evt);
            }
        });
        pu_carrera.add(a_del);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Estudiante");

        jLabel14.setText("Nombre");

        jLabel15.setText("Apellido");

        jLabel16.setText("Genero");

        jLabel18.setText("Cuenta");

        jLabel19.setText("Edad");

        jLabel20.setText("Carrera");

        buttonGroup2.add(a_men);
        a_men.setText("M");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("F");

        a_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_apellidoActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Guardar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_estudiantesLayout = new javax.swing.GroupLayout(jd_estudiantes.getContentPane());
        jd_estudiantes.getContentPane().setLayout(jd_estudiantesLayout);
        jd_estudiantesLayout.setHorizontalGroup(
            jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_estudiantesLayout.createSequentialGroup()
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_estudiantesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20))
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))))
                        .addGap(29, 29, 29)
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(a_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a_men, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addComponent(jc_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGap(212, 212, 212)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_estudiantesLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(101, 101, 101)
                                .addComponent(jRadioButton4))
                            .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_estudiantesLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(a_nombre))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_estudiantesLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(18, 18, 18)
                                    .addComponent(a_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jd_estudiantesLayout.setVerticalGroup(
            jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(a_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(a_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_estudiantesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(a_men)
                            .addComponent(jRadioButton4))
                        .addGap(24, 24, 24)
                        .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_estudiantesLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(a_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(jd_estudiantesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jd_estudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jc_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jLabel17.setText("jLabel17");

        jRadioButton3.setText("jRadioButton3");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        mod.setText("Modificar");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        pu_estudiantes.add(mod);

        del.setText("Eliminar");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        pu_estudiantes.add(del);

        jLabel21.setText("jLabel21");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Clases");

        jLabel26.setText("Nombre");

        jLabel27.setText("Seccion");

        jLabel28.setText("Edificio");

        jLabel29.setText("Salon");

        jLabel30.setText("Aire Acondicionado:");

        buttonGroup4.add(yes);
        yes.setText("SI");

        buttonGroup4.add(jRadioButton5);
        jRadioButton5.setText("NO");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Guardar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_clasesLayout = new javax.swing.GroupLayout(jd_clases.getContentPane());
        jd_clases.getContentPane().setLayout(jd_clasesLayout);
        jd_clasesLayout.setHorizontalGroup(
            jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clasesLayout.createSequentialGroup()
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_clasesLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_clasesLayout.createSequentialGroup()
                        .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_clasesLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel26))
                            .addGroup(jd_clasesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)
                                    .addGroup(jd_clasesLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel28)))))
                        .addGap(18, 18, 18)
                        .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_clasesLayout.createSequentialGroup()
                                .addComponent(b_edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_clasesLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(yes)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(513, 513, 513))
        );
        jd_clasesLayout.setVerticalGroup(
            jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_clasesLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(b_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(b_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(b_edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_clasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(b_salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel30)
                .addGap(29, 29, 29)
                .addComponent(yes)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        bmod.setText("Modificar");
        bmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodActionPerformed(evt);
            }
        });
        pu_clases.add(bmod);

        bdel.setText("Eliminar");
        bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelActionPerformed(evt);
            }
        });
        pu_clases.add(bdel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administracion Unitec");

        jButton1.setText("Crear Carrera");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Estudiante");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Crear Clases");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Crear Maestros");

        jLabel3.setText("Lista Carreras");

        jLabel4.setText("Lista Estudiantes");

        jLabel5.setText("Lista Clases");

        jLabel6.setText("Lista Maestros");

        jl_carrera.setModel(new DefaultListModel());
        jl_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_carreraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_carrera);

        jl_estudiantes.setModel(new DefaultListModel());
        jl_estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_estudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_estudiantes);

        jl_clases.setModel(new DefaultListModel());
        jl_clases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_clasesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_clases);

        jl_maestros.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_maestros);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Arbol");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jTree1);

        jLabel22.setText("Porfavor Crear Carrera Primero");

        jLabel23.setText("Porfavor Crear Clase Primero");

        jLabel24.setText("Usar Right Click para Editar y eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel3)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(385, 385, 385)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(303, 303, 303)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(419, 419, 419))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(59, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_carrera.setModal(true); //no poder tocar a principal
        jd_carrera.pack();//tamaño se acople a los controles preestablecidos
        jd_carrera.setLocationRelativeTo(this);//centro de la principal
        jd_carrera.setVisible(true);

    }//GEN-LAST:event_jButton1MouseClicked

    private void a_ingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_ingActionPerformed
        // TODO add your handling code here:\
        jc_ing.setVisible(true);
        jc_lics.setVisible(false);
        jc_doc.setVisible(false);

    }//GEN-LAST:event_a_ingActionPerformed

    private void a_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_docActionPerformed
        // TODO add your handling code here:
        jc_doc.setVisible(true);
        jc_lics.setVisible(false);
        jc_ing.setVisible(false);

    }//GEN-LAST:event_a_docActionPerformed

    private void r_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_lActionPerformed
        // TODO add your handling code here:
        jc_doc.setVisible(false);
        jc_lics.setVisible(true);
        jc_ing.setVisible(false);
    }//GEN-LAST:event_r_lActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        try {
            String facultad = "";
            double costo = Double.parseDouble(a_costo.getText());
            String jefe = a_jefe.getText();

            if (r_l.isSelected()) {
                facultad = "Licensiatura";
                String nombre = "";
                if (jc_lics.getSelectedIndex() == 0) {
                    nombre = "Finanzas";
                }

                if (jc_lics.getSelectedIndex() == 1) {
                    nombre = "Derecho";
                }
                if (jc_lics.getSelectedIndex() == 2) {
                    nombre = "Empresas";
                }
                if (jc_lics.getSelectedIndex() == 3) {
                    nombre = "Diseno";
                }
                if (jc_lics.getSelectedIndex() == 4) {
                    nombre = "Mercadotecnia";
                }
                Carrera c = new Carrera(nombre, facultad, jefe, costo);
                DefaultListModel modelo = (DefaultListModel) jl_carrera.getModel();
                modelo.addElement(c);
                jl_carrera.setModel(modelo);
                a_costo.setText("");
                a_jefe.setText("");
                JOptionPane.showMessageDialog(this, "Carrera Creada Exitosamente");

                lista1.add(c);
                ///
                DefaultComboBoxModel dc2 = (DefaultComboBoxModel) jc_carrera.getModel();
                dc2.addElement(c);
                jc_carrera.setModel(dc2);

            }///
            if (a_ing.isSelected()) {
                facultad = "Ingeneria";
                String nombre = "";
                if (jc_ing.getSelectedIndex() == 0) {

                    nombre = "Sistemas";
                }
                if (jc_ing.getSelectedIndex() == 1) {

                    nombre = "industrial";
                }
                if (jc_ing.getSelectedIndex() == 2) {

                    nombre = "mecatronica";
                }
                if (jc_ing.getSelectedIndex() == 3) {

                    nombre = "Biomedica";
                }
                if (jc_ing.getSelectedIndex() == 4) {

                    nombre = "energia";
                }
                Carrera c = new Carrera(nombre, facultad, jefe, costo);
                DefaultListModel modelo = (DefaultListModel) jl_carrera.getModel();
                modelo.addElement(c);
                jl_carrera.setModel(modelo);
                a_costo.setText("");
                a_jefe.setText("");
                JOptionPane.showMessageDialog(this, "Carrera Creada Exitosamente");

                lista1.add(c);
                DefaultComboBoxModel dc2 = (DefaultComboBoxModel) jc_carrera.getModel();
                dc2.addElement(c);
                jc_carrera.setModel(dc2);
            }
            if (a_doc.isSelected()) {
                String nombre = "";
                facultad = "Ciensas Salud";
                if (jc_doc.getSelectedIndex() == 0) {
                    nombre = "Medicina";
                }
                if (jc_doc.getSelectedIndex() == 1) {
                    nombre = "Odontolgia";
                }
                if (jc_doc.getSelectedIndex() == 2) {
                    nombre = "Nutricion";
                }
                if (jc_doc.getSelectedIndex() == 3) {
                    nombre = "Terapia";
                }
                Carrera c = new Carrera(nombre, facultad, jefe, costo);
                DefaultListModel modelo = (DefaultListModel) jl_carrera.getModel();
                modelo.addElement(c);
                jl_carrera.setModel(modelo);
                a_costo.setText("");
                a_jefe.setText("");
                JOptionPane.showMessageDialog(this, "Carrera Creada Exitosamente");

                lista1.add(c);
                DefaultComboBoxModel dc2 = (DefaultComboBoxModel) jc_carrera.getModel();
                dc2.addElement(c);
                jc_carrera.setModel(dc2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio Error");
        }


    }//GEN-LAST:event_jButton5MouseClicked

    private void jl_carreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_carreraMouseClicked
        // TODO add your handling code here:
        if (jl_carrera.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pu_carrera.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_carreraMouseClicked

    private void a_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_delActionPerformed
        // TODO add your handling code here:
        if (jl_carrera.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_carrera.getModel();
            modelo.remove(jl_carrera.getSelectedIndex());
            jl_carrera.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

        }
    }//GEN-LAST:event_a_delActionPerformed

    private void a_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_modActionPerformed
        // TODO add your handling code here:
        if (jl_carrera.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_carrera.getModel();
            ((Carrera) modeloLISTA.get(
                    jl_carrera.getSelectedIndex())).
                    setNombre(JOptionPane.showInputDialog("nombre"));
            jl_carrera.setModel(modeloLISTA);

        }
    }//GEN-LAST:event_a_modActionPerformed

    private void jl_estudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_estudiantesMouseClicked
        // TODO add your handling code here:
        if (jl_estudiantes.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pu_estudiantes.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }

    }//GEN-LAST:event_jl_estudiantesMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_estudiantes.setModal(true); //no poder tocar a principal
        jd_estudiantes.pack();//tamaño se acople a los controles preestablecidos
        jd_estudiantes.setLocationRelativeTo(this);//centro de la principal
        jd_estudiantes.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void a_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_apellidoActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        try {
            String nombre = a_nombre.getText();
            String apellido = a_apellido.getText();
            String genero = "";
            if (a_men.isSelected()) {
                genero = "  Masculino";
            } else {
                genero = "Femenino";
            }
            int cuenta = Integer.parseInt(a_cuenta.getText());
            int edad = (Integer) a_edad.getValue();
            Carrera c = (Carrera) jc_carrera.getSelectedItem();
            Estudiantes e = new Estudiantes(nombre, apellido, genero, cuenta, edad, c);
            DefaultListModel modelo = (DefaultListModel) jl_estudiantes.getModel();
            modelo.addElement(e);
            jl_estudiantes.setModel(modelo);
            lista2.add(e);
            JOptionPane.showMessageDialog(this, "Creado Exitosamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO ERROR");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        if (jl_estudiantes.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_estudiantes.getModel();
            modelo.remove(jl_estudiantes.getSelectedIndex());
            jl_estudiantes.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

        }
    }//GEN-LAST:event_delActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        if (jl_estudiantes.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_estudiantes.getModel();
            ((Estudiantes) modeloLISTA.get(
                    jl_estudiantes.getSelectedIndex())).
                    setNombre(JOptionPane.showInputDialog("nombre"));
            jl_estudiantes.setModel(modeloLISTA);

        }
    }//GEN-LAST:event_modActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jd_clases.setModal(true); //no poder tocar a principal
        jd_clases.pack();//tamaño se acople a los controles preestablecidos
        jd_clases.setLocationRelativeTo(this);//centro de la principal
        jd_clases.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = b_nombre.getText();
            String seccion = b_seccion.getText();
            int e = (Integer) b_edificio.getValue();
            int sa = (Integer) b_salon.getValue();
            String acon = "";
            if (yes.isSelected()) {
                acon = " Si hay aire";
            } else {
                acon = " no hay aire";
            }
            Clases cs = new Clases(nombre, seccion, e, sa, acon);
            DefaultListModel modelo = (DefaultListModel) jl_clases.getModel();
            modelo.addElement(cs);
            jl_clases.setModel(modelo);
            lista3.add(cs);
            JOptionPane.showMessageDialog(this, "Clase Creada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO ERROR");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jl_clasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_clasesMouseClicked
        // TODO add your handling code here:
           // TODO add your handling code here:
        if (jl_clases.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pu_clases.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_clasesMouseClicked

    private void bmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodActionPerformed
        // TODO add your handling code here:
        if (jl_clases.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_clases.getModel();
            ((Clases) modeloLISTA.get(
                    jl_clases.getSelectedIndex())).
                    setNombre(JOptionPane.showInputDialog("nombre"));
            jl_clases.setModel(modeloLISTA);

        }
    }//GEN-LAST:event_bmodActionPerformed

    private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
        // TODO add your handling code here:
        if (jl_clases.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_clases.getModel();
            modelo.remove(jl_clases.getSelectedIndex());
            jl_clases.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

        }
    }//GEN-LAST:event_bdelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_apellido;
    private javax.swing.JTextField a_costo;
    private javax.swing.JTextField a_cuenta;
    private javax.swing.JMenuItem a_del;
    private javax.swing.JRadioButton a_doc;
    private javax.swing.JSpinner a_edad;
    private javax.swing.JRadioButton a_ing;
    private javax.swing.JTextField a_jefe;
    private javax.swing.JRadioButton a_men;
    private javax.swing.JMenuItem a_mod;
    private javax.swing.JTextField a_nombre;
    private javax.swing.JSpinner b_edificio;
    private javax.swing.JTextField b_nombre;
    private javax.swing.JSpinner b_salon;
    private javax.swing.JTextField b_seccion;
    private javax.swing.JMenuItem bdel;
    private javax.swing.JMenuItem bmod;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JMenuItem del;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> jc_carrera;
    private javax.swing.JComboBox<String> jc_doc;
    private javax.swing.JComboBox<String> jc_ing;
    private javax.swing.JComboBox<String> jc_lics;
    private javax.swing.JDialog jd_carrera;
    private javax.swing.JDialog jd_clases;
    private javax.swing.JDialog jd_estudiantes;
    private javax.swing.JList<String> jl_carrera;
    private javax.swing.JList<String> jl_clases;
    private javax.swing.JList<String> jl_estudiantes;
    private javax.swing.JList<String> jl_maestros;
    private javax.swing.JMenuItem mod;
    private javax.swing.JPopupMenu pu_carrera;
    private javax.swing.JPopupMenu pu_clases;
    private javax.swing.JPopupMenu pu_estudiantes;
    private javax.swing.JRadioButton r_l;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables
    ArrayList<Carrera> lista1 = new ArrayList();
    ArrayList<Estudiantes> lista2 = new ArrayList();
    ArrayList<Clases> lista3 = new ArrayList();

}
